/**
 * Builds the probe into `dist/`, corpus and all.
 *
 *     npm run probe:build
 *
 * A plugin bundle cannot read the repository once it is running in a
 * vault, so the note fixtures are read here and generated into the module
 * the plugin imports as `probe-corpus`. They come through the harness
 * loader, which is the one enumeration of the corpus; a fixture on disk
 * that the loader does not list fails the build rather than going missing
 * from every run quietly.
 *
 * The output is `dist/main.js` and `dist/manifest.json`, which is the pair
 * a vault's plugin folder wants.
 */

import { copyFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Buffer } from 'node:buffer';
import esbuild from 'esbuild';
import {
	NOTE_FIXTURES,
	noteFixtureNamesOnDisk,
} from '../../test/harness/fixtures/note-corpus.ts';

const CORPUS_MODULE = 'probe-corpus';

const here = new URL('./', import.meta.url);
const distribution = new URL('./dist/', here);
const banner = `/*
GENERATED BY ESBUILD from tools/a11-probe/ in the davenport repository.
The note corpus is embedded; the source is under test/harness/fixtures/notes/.
*/
`;

const embedded = NOTE_FIXTURES.map((fixture) => fixture.id).sort();
const onDisk = noteFixtureNamesOnDisk();
if (embedded.join(',') !== onDisk.join(',')) {
	console.error(
		`probe build: the loader enumerates ${embedded.join(', ')}, the fixture directory holds ${onDisk.join(', ')}`,
	);
	process.exit(1);
}

mkdirSync(fileURLToPath(distribution), { recursive: true });

await esbuild.build({
	banner: { js: banner },
	entryPoints: [fileURLToPath(new URL('./main.ts', here))],
	outfile: fileURLToPath(new URL('./main.js', distribution)),
	bundle: true,
	platform: 'browser',
	format: 'cjs',
	target: 'es2021',
	external: ['obsidian', 'electron'],
	treeShaking: true,
	sourcemap: false,
	minify: false,
	logLevel: 'info',
	plugins: [corpusPlugin(NOTE_FIXTURES)],
});

copyFileSync(
	fileURLToPath(new URL('./manifest.json', here)),
	fileURLToPath(new URL('./manifest.json', distribution)),
);

const bytes = NOTE_FIXTURES.reduce(
	(total, fixture) => total + Buffer.byteLength(fixture.content, 'utf8'),
	0,
);
console.log(
	`probe build: ${NOTE_FIXTURES.length} fixtures embedded, ${bytes} bytes of note text`,
);
console.log(
	'probe build: wrote tools/a11-probe/dist/main.js and manifest.json',
);
console.log(
	'probe build: copy that folder into a vault as davenport-a11-probe; tools/a11-probe/README.md has the path',
);

/** Serves the corpus as a module, since there is no file to import. */
function corpusPlugin(fixtures) {
	const contents = `export const PROBE_CORPUS = ${JSON.stringify(
		fixtures.map(({ id, fileName, content }) => ({
			id,
			fileName,
			content,
		})),
		null,
		'\t',
	)};\n`;
	return {
		name: CORPUS_MODULE,
		setup(build) {
			build.onResolve({ filter: /^probe-corpus$/ }, () => ({
				path: CORPUS_MODULE,
				namespace: CORPUS_MODULE,
			}));
			build.onLoad({ filter: /.*/, namespace: CORPUS_MODULE }, () => ({
				contents,
				loader: 'js',
			}));
		},
	};
}
