/**
 * The writer of the module that holds the timezone table.
 *
 * The plugin ships the table as source, because the engine reads no file
 * at run time and the bundle must hold every byte that the plugin needs.
 * This module turns the table text into that source.
 *
 * The text sits in a template string. The writer refuses a table that
 * holds a character which such a string reads as code. The module
 * therefore never carries an escape, and the bytes of the table stay the
 * bytes that the reader receives.
 */

/** The path of the module, for the message that the generator prints. */
export const TABLE_MODULE_PATH = 'src/core/timezone/table-data.ts';

/** The TypeScript source of the module that holds the table. */
export function tableModule(release: string, table: string): string {
	refuseTemplateCharacters(table);
	if (!/^[0-9]{4}[a-z]$/.test(release)) {
		throw new Error(
			`the release ${release} does not read as a release of the timezone database`,
		);
	}
	return `${HEAD}
/** The release of the timezone database that this table comes from. */
export const TIMEZONE_TABLE_RELEASE = '${release}';

/**
 * The table. One line states one timezone identifier. The comment at the
 * head of the decoder states the form of a line.
 */
export const TIMEZONE_TABLE = \`${table.trimEnd()}\`;
`;
}

const HEAD = `/**
 * The timezone table, as the generator wrote it.
 *
 * Do not edit this file. The generator under tools/timezone-table/ writes
 * it from the timezone database release that the same directory holds.
 * The README of that directory states how to write the file again and how
 * to check the release that it comes from.
 *
 * The data of the timezone database is in the public domain.
 */
`;

function refuseTemplateCharacters(table: string): void {
	const marks: readonly (readonly [string, string])[] = [
		['`', 'a back quote'],
		['\\', 'a back slash'],
		['${', 'the start of a substitution'],
	];
	for (const [mark, name] of marks) {
		const at = table.indexOf(mark);
		if (at !== -1) {
			throw new Error(
				`the table holds ${name} at ${String(at)}, and a template string reads it as code`,
			);
		}
	}
}
