import esbuild from 'esbuild';
import process from 'process';
import { writeFileSync } from 'node:fs';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	// The metafile says which module holds which bytes of the output.
	// `scripts/bundle-size.mjs` reads it. The watch build never writes it.
	metafile: prod,
	// A content hash in the name of a chunk makes each rebuild of that chunk
	// read as an output file that went away, and the timezone data will
	// rebuild its chunk several times a year.
	chunkNames: '[name]',
});

if (prod) {
	const result = await context.rebuild();
	if (result.metafile === undefined) {
		throw new Error('the production build made no metafile');
	}
	writeFileSync(
		new URL('bundle-meta.json', import.meta.url),
		`${JSON.stringify(result.metafile, undefined, '\t')}\n`,
	);
	process.exit(0);
} else {
	await context.watch();
}
