import esbuild from 'esbuild';
import process from 'process';
import { writeFileSync } from 'node:fs';
import { builtinModules } from 'node:module';

// esbuild keeps a comment only when that comment carries @license or
// @preserve, or when the comment starts with an exclamation mark. The
// header of ical.js carries no such mark, so the bundle loses that header.
// This banner carries the notice of ical.js instead.
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
/*!
Davenport uses ical.js to read and write iCalendar data. ical.js is
Copyright (C) Philipp Kewisch.
ical.js is under the Mozilla Public License 2.0, and the code of ical.js
in this file stays under that license.
A copy of the license is at https://mozilla.org/MPL/2.0/.
The source of the version in this file is at
https://github.com/kewisch/ical.js/releases/tag/v2.2.1
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	// The metafile says which module holds which bytes of the output.
	// `scripts/bundle-size.mjs` reads it. The watch build never writes it.
	metafile: prod,
	// A content hash in the name of a chunk makes each rebuild of that chunk
	// read as an output file that went away, and the timezone data will
	// rebuild its chunk several times a year.
	chunkNames: '[name]',
});

if (prod) {
	const result = await context.rebuild();
	if (result.metafile === undefined) {
		throw new Error('the production build made no metafile');
	}
	writeFileSync(
		new URL('bundle-meta.json', import.meta.url),
		`${JSON.stringify(result.metafile, undefined, '\t')}\n`,
	);
	process.exit(0);
} else {
	await context.watch();
}
